In [2]:
import numpy as np

In [3]:
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

In [4]:
arr1

array([[2, 1, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [5]:
arr1.flatten() #Return a copy of the array collapsed into one dimension.

array([2, 1, 1, 2, 1, 1, 2, 2, 2])

In [6]:
#expand dimesnion
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [7]:
arr.ndim

1

In [8]:
np.expand_dims(arr, axis = 0) #increases the dimension by 1 at provoided axis
# axis = 0 means interms of row 
# axis = 1 means interms of col

array([[1, 2, 3, 4]])

In [9]:
np.expand_dims(arr, axis = 1)

array([[1],
       [2],
       [3],
       [4]])

In [10]:
np.expand_dims(arr, axis = 1).ndim # initially it was 1 but now its 2 

2

In [11]:
arr

array([1, 2, 3, 4])

In [12]:
arr = np.zeros((3, 4))

In [13]:
arr.ndim

2

In [14]:
np.expand_dims(arr, axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
np.expand_dims(arr, axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [16]:
np.expand_dims(arr, axis=0).ndim

3

In [17]:

a = np.array([[1], [2], [3]])



In [18]:
a

array([[1],
       [2],
       [3]])

In [19]:
a.ndim

2

In [20]:
np.squeeze(a) #Remove axes of length one from `a`

array([1, 2, 3])

In [21]:
a

array([[1],
       [2],
       [3]])

In [22]:
np.repeat(a, 4) # repeats each element for a given amount of times

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [23]:
arr1

array([[2, 1, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [24]:
np.repeat(arr1,2)

array([2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2])

In [25]:
np.repeat(arr1, 2, axis=0) # it will repeat row wise

array([[2, 1, 1],
       [2, 1, 1],
       [2, 1, 1],
       [2, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [26]:
np.repeat(arr1, 3, axis=0)

array([[2, 1, 1],
       [2, 1, 1],
       [2, 1, 1],
       [2, 1, 1],
       [2, 1, 1],
       [2, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [27]:
np.repeat(arr1, 3, axis=1) # it will repeat col wise 

array([[2, 2, 2, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [28]:
a

array([[1],
       [2],
       [3]])

In [29]:
np.roll(a, -1)

array([[2],
       [3],
       [1]])

In [30]:
np.roll(a, -2)

array([[3],
       [1],
       [2]])

In [31]:
c = np.array([[1,2], [3, 4], [5,6], [7,8]])

In [32]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [33]:
np.roll(c, 2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [34]:
np.roll(c, 2, axis=0) # to roll properly u must provide the axis to be rolled

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [35]:
arr1

array([[2, 1, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [36]:
arr2

array([[2, 1, 2],
       [1, 1, 1],
       [2, 1, 1]])

In [37]:
arr1 + arr2

array([[4, 2, 3],
       [3, 2, 2],
       [4, 3, 3]])

In [38]:
arr1 - arr2

array([[ 0,  0, -1],
       [ 1,  0,  0],
       [ 0,  1,  1]])

In [39]:
arr1 *arr2

array([[4, 1, 2],
       [2, 1, 1],
       [4, 2, 2]])

In [40]:
arr1 > arr2

array([[False, False, False],
       [ True, False, False],
       [False,  True,  True]])

In [41]:
arr1

array([[2, 1, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [42]:
~arr1

array([[-3, -2, -2],
       [-3, -2, -2],
       [-3, -3, -3]])

In [43]:
# operations on numpy strings

In [44]:
d = np.array(["pw", "skills"])

In [45]:
d

array(['pw', 'skills'], dtype='<U6')

In [46]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [47]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [48]:
# thats it 

#### Mathematical functions

In [49]:
arr1

array([[2, 1, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [50]:
np.sin(arr1)

array([[0.90929743, 0.84147098, 0.84147098],
       [0.90929743, 0.84147098, 0.84147098],
       [0.90929743, 0.90929743, 0.90929743]])

In [51]:
np.cos(arr1)

array([[-0.41614684,  0.54030231,  0.54030231],
       [-0.41614684,  0.54030231,  0.54030231],
       [-0.41614684, -0.41614684, -0.41614684]])

In [52]:
np.tan(arr1)

array([[-2.18503986,  1.55740772,  1.55740772],
       [-2.18503986,  1.55740772,  1.55740772],
       [-2.18503986, -2.18503986, -2.18503986]])

In [53]:
np.log10(arr1)

array([[0.30103, 0.     , 0.     ],
       [0.30103, 0.     , 0.     ],
       [0.30103, 0.30103, 0.30103]])

In [54]:
np.exp(arr1)

array([[7.3890561 , 2.71828183, 2.71828183],
       [7.3890561 , 2.71828183, 2.71828183],
       [7.3890561 , 7.3890561 , 7.3890561 ]])

In [55]:
np.power(arr1, 3)

array([[8, 1, 1],
       [8, 1, 1],
       [8, 8, 8]])

In [56]:
np.mean(arr1)

1.5555555555555556

In [57]:
np.max(arr1)

2

In [58]:
np.min(arr1)

1

In [59]:
np.std(arr1) # standard deviation

0.4969039949999533

In [60]:
np.var(arr1) # variance

0.2469135802469136

In [61]:
arr1-arr2

array([[ 0,  0, -1],
       [ 1,  0,  0],
       [ 0,  1,  1]])

In [62]:
# alternate way to subtract
np.subtract(arr1, arr2)

array([[ 0,  0, -1],
       [ 1,  0,  0],
       [ 0,  1,  1]])

In [63]:
# similarly 

In [64]:
arr1 *arr2


array([[4, 1, 2],
       [2, 1, 1],
       [4, 2, 2]])

In [65]:
np.multiply(arr1, arr2)

array([[4, 1, 2],
       [2, 1, 1],
       [4, 2, 2]])

In [66]:
np.mod(arr1, arr2) #return elment wise remainder

array([[0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [67]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.        ],
       [1.41421356, 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356]])

## sort search

In [68]:
e = np.array([5, 6, 1, 2])

In [69]:
e

array([5, 6, 1, 2])

In [70]:
np.sort(e)

array([1, 2, 5, 6])

In [71]:
f = np.array([5, 199, 200, 6, 7, 8])

In [72]:
np.sort(f)

array([  5,   6,   7,   8, 199, 200])

In [73]:
np.searchsorted(f, 170) #Find indices where elements should be inserted to maintain order.

6

In [74]:
f = np.array([5, 199, 200, 6, 7, 0, 0, 0, 8])

In [75]:
np.count_nonzero(f)

6

In [76]:
f[f > 0]

array([  5, 199, 200,   6,   7,   8])

In [77]:
np.where(f>0) # it is what it is

(array([0, 1, 2, 3, 4, 8]),)

In [78]:
np.extract(f>0, f)

array([  5, 199, 200,   6,   7,   8])

In [79]:
f

array([  5, 199, 200,   6,   7,   0,   0,   0,   8])

In [80]:
f.byteswap()

array([  360287970189639680, -4107282860161892352, -4035225266123964416,
         432345564227567616,   504403158265495552,                    0,
                          0,                    0,   576460752303423488])

In [81]:
#matrix>> 2d array

import numpy.matlib as nm

In [82]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [83]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [84]:
#numpy linear algebra

arr1 = np.random.randint(1, 10, (3, 3))
arr2 = np.random.randint(1, 10, (3, 3))

In [85]:
arr1

array([[3, 7, 1],
       [9, 8, 5],
       [9, 7, 6]])

In [86]:
arr2

array([[4, 7, 7],
       [6, 3, 2],
       [7, 9, 3]])

In [87]:
arr1 @ arr2 # matrix multiplication ( not element wise)

array([[ 61,  51,  38],
       [119, 132,  94],
       [120, 138,  95]])

In [88]:
np.linalg.det(arr1) # determinant value

-33.0

In [89]:
np.linalg.inv(arr1) # inverse of the matrix 

array([[-0.39393939,  1.06060606, -0.81818182],
       [ 0.27272727, -0.27272727,  0.18181818],
       [ 0.27272727, -1.27272727,  1.18181818]])

In [90]:
a = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [91]:
b = np.array([16, 8, 0])
b

array([16,  8,  0])

In [92]:
np.linalg.solve(a, b)  # -->> 

array([2.59630607, 0.84432718, 2.21635884])