In [3]:
import numpy as np


In [4]:
a = np.zeros(5) # returns a new array of given shape and type

In [5]:
a.ndim

1

In [6]:
b = np.zeros((3,4)) # 3 rows and 4 columns 

In [7]:
b.ndim
b.shape

(3, 4)

In [8]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((3,4)) # same but works for ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
 # now to create with elements 2 -> no direct function
np.array(([2,2,2],[2,2,2]))

array([[2, 2, 2],
       [2, 2, 2]])

In [11]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# 3d array
arr = np.zeros((3,4))
arr.ndim

arr2 = np.zeros((1,3,4))
arr2


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [13]:
arr2.ndim

3

In [14]:
# 4d array / more 

arr = np.zeros((1,1,1,1,1,1,1)) # -> 7 dimensionsal 
arr.ndim


7

In [15]:
arr = np.ones((3,4))


In [16]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
arr+5 # adds 5 to eveyr element

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [18]:
arr/6

array([[0.16666667, 0.16666667, 0.16666667, 0.16666667],
       [0.16666667, 0.16666667, 0.16666667, 0.16666667],
       [0.16666667, 0.16666667, 0.16666667, 0.16666667]])

In [19]:
arr*38388383

array([[38388383., 38388383., 38388383., 38388383.],
       [38388383., 38388383., 38388383., 38388383.],
       [38388383., 38388383., 38388383., 38388383.]])

In [20]:
a = arr*5

In [21]:
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [22]:
a = a/5

In [23]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# special funcitons

In [24]:
np.eye(3) #Return a 2-D array with ones on the diagonal and zeros elsewhere.
# these are floats

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [26]:
np.empty((3, 4)) #Return a new array of given shape and type, without initializing entries

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
#optional >> random module

import random
print(random.choice((1, 2, 3, 4, 5)))
print(random.choice('Ajay'))
print(random.random()) # a random no is generated between 0(included) and 1 (excluded)
lis = [1, 2, 3, 4, 5]
print(random.shuffle(lis))
print(random.uniform(7, 14))

#random numbers related concepts in numpy

print(np.array([])) #Generates random floating-point numbers between 0 (inclusive) and 1 (exclusive).

print(np.random.random_sample((5, )))  # in NumPy generates a one-dimensional array (a row vector) containing five random floating-point numbers between 0 (inclusive) and 1 (exclusive).
print()
print()


2
y
0.479863400168308
None
10.81247412062667
[]
[0.7339484 0.3391217 0.6223851 0.6926543 0.9089102]




In [28]:
np.random.rand(1) # 1 random element array 1d

array([0.79483469])

In [39]:
np.random.randn(2,3)  # random number of the provided characters
# note : these numbers come from a random distribution population

array([[-7.33850617e-01, -4.47420660e-01, -1.76124026e+00],
       [ 5.95771317e-04, -2.37384241e-01, -4.38366252e-02]])

In [30]:
arr = np.random.randint(1, 5, size= (3, 4)) # from 1 to. 5 (excluded)
print(arr)
print(arr.ndim)
print(arr.size)
print(arr.shape)

[[2 1 3 4]
 [2 4 1 1]
 [2 2 4 3]]
2
12
(3, 4)


## reshaping the array 

In [31]:
arr1 = arr.reshape(2, 6) #array size will not change, always resape parameter should be multiplication of original array size

In [32]:
arr1

array([[2, 1, 3, 4, 2, 4],
       [1, 1, 2, 2, 4, 3]])

In [33]:
arr.reshape(12,1)

array([[2],
       [1],
       [3],
       [4],
       [2],
       [4],
       [1],
       [1],
       [2],
       [2],
       [4],
       [3]])

In [34]:
arr.reshape(1, 12)

array([[2, 1, 3, 4, 2, 4, 1, 1, 2, 2, 4, 3]])

In [36]:
# arr.reshape(3, 3) # throws an array due to a different size

In [37]:
arr.reshape(3,4)

array([[2, 1, 3, 4],
       [2, 4, 1, 1],
       [2, 2, 4, 3]])

In [52]:
#case when you dont know in reshape what should be the column count

arr.reshape(4, -1)





array([[2, 1, 3],
       [4, 2, 4],
       [1, 1, 2],
       [2, 4, 3]])

In [54]:
arr.reshape(2, -1)


array([[2, 1, 3, 4, 2, 4],
       [1, 1, 2, 2, 4, 3]])

In [55]:
arr.reshape(2, -100)

array([[2, 1, 3, 4, 2, 4],
       [1, 1, 2, 2, 4, 3]])

In [59]:
#you know column count but no row count
arr1 = arr.reshape(-1, 3)
arr1

array([[2, 1, 3],
       [4, 2, 4],
       [1, 1, 2],
       [2, 4, 3]])

In [60]:
 #to see the original array
arr.reshape(12, 1).base

array([[2, 1, 3, 4],
       [2, 4, 1, 1],
       [2, 2, 4, 3]])

In [63]:
# you can also reshape it into more dimensions
arr.reshape(2, 2, 3) # 2 times repeat 2*3 matrix



array([[[2, 1, 3],
        [4, 2, 4]],

       [[1, 1, 2],
        [2, 4, 3]]])

In [50]:
arr.reshape(1, 2, 2, 3)

array([[[[2, 1, 3],
         [4, 2, 4]],

        [[1, 1, 2],
         [2, 4, 3]]]])

In [61]:
arr.reshape(1, 2, 2, 3).ndim

4

In [62]:
arr.reshape(4, 3, 1) #3 rows 1 column repeated 4 times in the third dimension

array([[[2],
        [1],
        [3]],

       [[4],
        [2],
        [4]],

       [[1],
        [1],
        [2]],

       [[2],
        [4],
        [3]]])

## conditions on array

In [65]:

arr1 = np.random.randint(1, 10, (5,6))

In [66]:
arr1

array([[1, 8, 6, 3, 5, 3],
       [1, 4, 9, 2, 3, 5],
       [3, 4, 3, 6, 8, 5],
       [5, 8, 7, 6, 4, 9],
       [3, 2, 5, 2, 4, 6]])

In [70]:
arr1 > 3

array([[False,  True,  True, False,  True, False],
       [False,  True,  True, False, False,  True],
       [False,  True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [False, False,  True, False,  True,  True]])

In [71]:
arr1[arr1>3]

array([8, 6, 5, 4, 9, 5, 4, 6, 8, 5, 5, 8, 7, 6, 4, 9, 5, 4, 6])

In [72]:
arr1[arr1<3]

array([1, 1, 2, 2, 2])

## accessing elements in array

In [67]:
# to access row
arr1[0]

array([1, 8, 6, 3, 5, 3])

In [68]:
# to accesss 0th element of 0th row
arr1[0][0]

1

In [69]:
# to access first 2 row 
arr1[0:2] # just like string slicing

array([[1, 8, 6, 3, 5, 3],
       [1, 4, 9, 2, 3, 5]])

In [73]:
arr1[0:3] #oth row, 1st row and 2nd row

array([[1, 8, 6, 3, 5, 3],
       [1, 4, 9, 2, 3, 5],
       [3, 4, 3, 6, 8, 5]])

In [74]:
arr1[0:3, [0, 2]] #0to2nd row and 0th and 2nd column

array([[1, 6],
       [1, 9],
       [3, 3]])

## slicing on both rows and column

In [75]:
arr1[0:3, 1:3]

array([[8, 6],
       [4, 9],
       [4, 3]])

In [76]:
arr1[0:2, [0,1]]

array([[1, 8],
       [1, 4]])

In [77]:
arr1[0, [1, 3]]

array([8, 3])

In [78]:
arr1[2:4, [0, 3]]

array([[3, 6],
       [5, 6]])

In [79]:
arr1[2:5]

array([[3, 4, 3, 6, 8, 5],
       [5, 8, 7, 6, 4, 9],
       [3, 2, 5, 2, 4, 6]])

In [80]:
arr1[2:5, 0:2]

array([[3, 4],
       [5, 8],
       [3, 2]])

## Mathematicaloperations on 2 arrays


In [81]:
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))

In [85]:
arr1+arr2 #index wise elment addition

array([[3, 3, 2],
       [3, 3, 2],
       [3, 3, 3]])

In [83]:
arr1-arr2 #indexwise element substraction

array([[-1,  1,  0],
       [-1, -1,  0],
       [ 1, -1, -1]])

In [84]:
arr1 * arr2 #index wise multiplication

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 2]])

In [86]:
arr1, arr2

(array([[1, 2, 1],
        [1, 1, 1],
        [2, 1, 1]]),
 array([[2, 1, 1],
        [2, 2, 1],
        [1, 2, 2]]))

In [87]:
arr1 / arr2 #index wise divison

array([[0.5, 2. , 1. ],
       [0.5, 0.5, 1. ],
       [2. , 0.5, 0.5]])

In [88]:
arr1 / 0 #in python zero divion error will come, but in numpy no error

/tmp/ipykernel_77/1550714841.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0 #in python zero divion error will come, but in numpy no error


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [89]:
#matrix multiplication>> different from index wise multiplication

arr1 @ arr2 #1st way to do matrix multiplication

array([[7, 7, 5],
       [5, 5, 4],
       [7, 6, 5]])

In [90]:
np.dot(arr1, arr2) #ndst way to do matrix multiplication

array([[7, 7, 5],
       [5, 5, 4],
       [7, 6, 5]])

In [91]:
arr = np.zeros((3, 4))

In [92]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [94]:
arr*44

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [95]:
a = np.array([1, 2, 3, 4]) # 1d array to explain vareuty of operation

In [96]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [97]:
#Transpose
a.T

array([1, 2, 3, 4])

In [98]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [99]:
arr.T

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [100]:
arr[:,0] # access col 0 

array([0., 0., 0.])

In [103]:
arr[2:3,0]

array([0.])

In [104]:
# to access col 1
arr[:,1]

array([0., 0., 0.])

In [105]:
arr5 = np.random.randint(1, 6, (5,5))

In [106]:
arr5

array([[4, 3, 1, 1, 4],
       [5, 3, 3, 5, 3],
       [1, 3, 4, 1, 5],
       [1, 3, 3, 2, 4],
       [3, 4, 4, 2, 3]])

In [107]:
np.sqrt(arr5) # another important function

array([[2.        , 1.73205081, 1.        , 1.        , 2.        ],
       [2.23606798, 1.73205081, 1.73205081, 2.23606798, 1.73205081],
       [1.        , 1.73205081, 2.        , 1.        , 2.23606798],
       [1.        , 1.73205081, 1.73205081, 1.41421356, 2.        ],
       [1.73205081, 2.        , 2.        , 1.41421356, 1.73205081]])

In [109]:
np.log10(arr5) # gives the values forr log 10

array([[0.60205999, 0.47712125, 0.        , 0.        , 0.60205999],
       [0.69897   , 0.47712125, 0.47712125, 0.69897   , 0.47712125],
       [0.        , 0.47712125, 0.60205999, 0.        , 0.69897   ],
       [0.        , 0.47712125, 0.47712125, 0.30103   , 0.60205999],
       [0.47712125, 0.60205999, 0.60205999, 0.30103   , 0.47712125]])

In [111]:
np.exp(arr1) # e^ elements

array([[2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [7.3890561 , 2.71828183, 2.71828183]])

In [112]:
np.min(arr5)

1

In [113]:
np.max(arr5)

5