In [ ]:
# numpy basics

In [4]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

In [3]:
print("helolaeo")

helolaeo


In [5]:
print("dfafaaf")

dfafaaf


In [6]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

In [8]:
#Numpy stores the data in an array
#An array is a container used to store the data of same data type
#why numpy
#Computation is fast>> due to array>>>continous memory location
#mathematical computation

In [9]:
l = [1, 2, 3, 4, 5]

In [10]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [15]:
# more similar conversions

l = [1, 2, 3, 4, 5.1]
arr = np.array(l)
print(arr) # all are converted to float

l = [1, 2, 3, 4, 5.1, "Ajay"]
arr = np.array(l)
print(arr)  # all are converted to string
type(arr) # -> numpy.ndarray

[1.  2.  3.  4.  5.1]
['1' '2' '3' '4' '5.1' 'Ajay']


numpy.ndarray

In [16]:
# more factual points and functions
# .ndim -> tells about the dimentsion of array
arr.ndim

1

In [17]:
l = [[1,2,3],[4,5,6]]
arr = np.array(l)
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [18]:
mat = np.matrix([1, 2, 3, 4]) #matrix is a specialised array, 2 dimensional

In [19]:
type(mat)

numpy.matrix

In [20]:
mat

matrix([[1, 2, 3, 4]])

In [28]:
np.matrix([[[1, 2], [3,4], [5,6]]]) # error because this is a 3d array

ValueError: matrix must be 2-dimensional

In [22]:
#To create an array >> np.array, np.asarray, np.asanyarray, deep copy and shallow copy
import numpy as np

# Original data
data = [1, 2, 3, 4, 5]

# Creating arrays using different methods
print("np.array:")
arr_np_array = np.array(data)
print(arr_np_array)

print("\nnp.asarray:")
arr_np_asarray = np.asarray(data)
print(arr_np_asarray)

print("\nnp.asanyarray:")
arr_np_asanyarray = np.asanyarray(data)
print(arr_np_asanyarray)

# Check if the original data is modified (data is immutable)
print("\nOriginal data:", data)

# Deep copy vs. shallow copy

# Original array
original_arr = np.array([10, 20, 30])

# Deep copy - modifications won't affect the original array
deep_copy = original_arr.copy()
print("\nDeep copy:")
print(deep_copy)
deep_copy[0] = 100
print(deep_copy)
print(original_arr)  # Original array remains unchanged

# Shallow copy - modifications will affect the original array
shallow_copy = original_arr.view()
print("\nShallow copy:")
print(shallow_copy)
shallow_copy[0] = 500
print(shallow_copy)
print(original_arr)  # Original array is also modified



np.array:
[1 2 3 4 5]

np.asarray:
[1 2 3 4 5]

np.asanyarray:
[1 2 3 4 5]

Original data: [1, 2, 3, 4, 5]

Deep copy:
[10 20 30]
[100  20  30]
[10 20 30]

Shallow copy:
[10 20 30]
[500  20  30]
[500  20  30]


In [23]:
arr1 = np.fromfunction(lambda i, j : i==j, (3,3)) #Construct an array by executing a function over each coordinate.

In [26]:
arr1
print(arr1)
print(arr1.ndim) # dimension of the created array
print(arr1.shape) # shape of elements
print(arr1.size) # no of elment present


[[ True False False]
 [False  True False]
 [False False  True]]
2
(3, 3)
9


In [27]:
arr2 = np.fromfunction(lambda i, j : i*j, (3,3)) 
print(arr2)
print(arr2.ndim) # dimension of the created array
print(arr2.shape) # shape of elements
print(arr2.size) # no of elment present


[[0. 0. 0.]
 [0. 1. 2.]
 [0. 2. 4.]]
2
(3, 3)
9


In [29]:
# many other ways of creating strings and using numpy
print([i for i in range(5)])
print(list((i for i in range(5))))



[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]


In [30]:
# create 1d array from iterable object
iterable = (i for i in range(5))
np.fromiter(iterable, int) 
iterable

<generator object <genexpr> at 0x7fe4c0342810>

In [31]:
np.fromstring('22 23 24', sep = " ") #values should be numerical

array([22., 23., 24.])

In [32]:
np.fromstring('22,23,24', sep = ",")

array([22., 23., 24.])

In [34]:
# amazing implementation

#for string character you have  to use split
string = 'Ajay,Bijay,Sanjay'
string1 = string.split(',')
np.array(string1)

array(['Ajay', 'Bijay', 'Sanjay'], dtype='<U6')

In [35]:
list(range(10))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
range(10)

range(0, 10)

In [37]:
#other methods of numpy>> to generate sequnce of nos
np.arange(1, 10, 0.1) #Return evenly spaced values within a given interval.

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [38]:
np.linspace(1, 5, 10)#Return evenly spaced numbers over a specified interval.
#give me 10 numbers between 1 and 5 evenly spaced

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])